#include "conditions/condition_language_catalog.h"

#include <algorithm>
#include <cctype>

namespace forevertas {
namespace {

using namespace forevervalidator::experimental;

std::string Lower(std::string_view value) {
    std::string result;
    result.reserve(value.size());
    for (const char c : value) {
        result.push_back(std::tolower(static_cast<unsigned char>(c)));
    }
    return result;
}

ConditionLanguageSymbol MakeScalarSymbol(
        std::string_view canonicalName,
        std::vector<std::string_view> aliases,
        std::string_view friendlyName,
        std::string_view category,
        std::string_view type,
        std::string_view unit,
        std::string_view detail,
        std::string_view documentation,
        std::string_view insertionTemplate,
        std::string_view example,
        PhysicsSandboxCudaConditionValue value,
        std::uint32_t component,
        bool pointTargetOnly = false,
        bool external = false) {
    return {canonicalName,
            std::move(aliases),
            friendlyName,
            category,
            type,
            unit,
            detail,
            documentation,
            insertionTemplate,
            example,
            pointTargetOnly,
            external,
            ConditionLanguageSymbolKind::Scalar,
            value,
            component};
}

ConditionLanguageSymbol MakeVectorSymbol(
        std::string_view canonicalName,
        std::vector<std::string_view> aliases,
        std::string_view friendlyName,
        std::string_view category,
        std::string_view type,
        std::string_view unit,
        std::string_view detail,
        std::string_view documentation,
        std::string_view insertionTemplate,
        std::string_view example,
        PhysicsSandboxCudaConditionValue value,
        bool pointTargetOnly = false,
        bool external = false) {
    return {canonicalName,
            std::move(aliases),
            friendlyName,
            category,
            type,
            unit,
            detail,
            documentation,
            insertionTemplate,
            example,
            pointTargetOnly,
            external,
            ConditionLanguageSymbolKind::Vector,
            value,
            0u};
}

ConditionLanguageFunction MakeFunction(
        std::string_view canonicalName,
        std::vector<std::string_view> aliases,
        std::string_view friendlyName,
        std::string_view category,
        std::string_view signature,
        std::string_view returnType,
        std::string_view documentation,
        std::string_view insertionTemplate,
        std::string_view example,
        ConditionLanguageFunctionKind kind,
        bool pointTargetOnly = false) {
    std::vector<ConditionLanguageValueType> parameterTypes;
    ConditionLanguageValueType resultType =
            ConditionLanguageValueType::Scalar;
    switch (kind) {
    case ConditionLanguageFunctionKind::KmH:
    case ConditionLanguageFunctionKind::Deg:
    case ConditionLanguageFunctionKind::TimeSince:
        parameterTypes = {ConditionLanguageValueType::Scalar};
        break;
    case ConditionLanguageFunctionKind::Distance:
        parameterTypes = {ConditionLanguageValueType::Vector,
                          ConditionLanguageValueType::Vector};
        break;
    case ConditionLanguageFunctionKind::VariableLookup:
        parameterTypes = {ConditionLanguageValueType::ExternalName};
        resultType = ConditionLanguageValueType::Dynamic;
        break;
    }
    return {canonicalName,
            std::move(aliases),
            friendlyName,
            category,
            signature,
            returnType,
            documentation,
            insertionTemplate,
            example,
            kind,
            pointTargetOnly,
            std::move(parameterTypes),
            resultType};
}

const std::vector<ConditionLanguageSymbol> &AllConditionSymbols() {
    static const std::vector<ConditionLanguageSymbol> symbols = {
            MakeScalarSymbol(
                    "car.x",
                    {"car.x", "car.position.x"},
                    "Current position X",
                    "vehicle",
                    "scalar",
                    "m",
                    "car current X axis position component",
                    "Current car world-space X position at the current tick.",
                    "car.x",
                    "car.x > 0",
                    PhysicsSandboxCudaConditionValue::Position,
                    1u),
            MakeScalarSymbol(
                    "car.y",
                    {"car.y", "car.position.y"},
                    "Current position Y",
                    "vehicle",
                    "scalar",
                    "m",
                    "car current Y axis position component",
                    "Current car world-space Y position at the current tick.",
                    "car.y",
                    "car.y > 0",
                    PhysicsSandboxCudaConditionValue::Position,
                    2u),
            MakeScalarSymbol(
                    "car.z",
                    {"car.z", "car.position.z"},
                    "Current position Z",
                    "vehicle",
                    "scalar",
                    "m",
                    "car current Z axis position component",
                    "Current car world-space Z position at the current tick.",
                    "car.z",
                    "car.z > 0",
                    PhysicsSandboxCudaConditionValue::Position,
                    3u),
            MakeScalarSymbol(
                    "car.prev.x",
                    {"car.prev.x", "car.prev.position.x"},
                    "Previous position X",
                    "vehicle",
                    "scalar",
                    "m",
                    "car previous X axis position component",
                    "Car world-space X position one tick earlier.",
                    "car.prev.x",
                    "car.prev.x < 2",
                    PhysicsSandboxCudaConditionValue::PreviousPosition,
                    1u),
            MakeScalarSymbol(
                    "car.prev.y",
                    {"car.prev.y", "car.prev.position.y"},
                    "Previous position Y",
                    "vehicle",
                    "scalar",
                    "m",
                    "car previous Y axis position component",
                    "Car world-space Y position one tick earlier.",
                    "car.prev.y",
                    "car.prev.y < 2",
                    PhysicsSandboxCudaConditionValue::PreviousPosition,
                    2u),
            MakeScalarSymbol(
                    "car.prev.z",
                    {"car.prev.z", "car.prev.position.z"},
                    "Previous position Z",
                    "vehicle",
                    "scalar",
                    "m",
                    "car previous Z axis position component",
                    "Car world-space Z position one tick earlier.",
                    "car.prev.z",
                    "car.prev.z < 2",
                    PhysicsSandboxCudaConditionValue::PreviousPosition,
                    3u),
            MakeScalarSymbol(
                    "car.vel.x",
                    {"car.vel.x", "car.velocity.x"},
                    "Current velocity X",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car current velocity along X",
                    "Current world-space X axis linear velocity component.",
                    "car.vel.x",
                    "car.vel.x > 2",
                    PhysicsSandboxCudaConditionValue::Velocity,
                    1u),
            MakeScalarSymbol(
                    "car.vel.y",
                    {"car.vel.y", "car.velocity.y"},
                    "Current velocity Y",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car current velocity along Y",
                    "Current world-space Y axis linear velocity component.",
                    "car.vel.y",
                    "car.vel.y > 2",
                    PhysicsSandboxCudaConditionValue::Velocity,
                    2u),
            MakeScalarSymbol(
                    "car.vel.z",
                    {"car.vel.z", "car.velocity.z"},
                    "Current velocity Z",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car current velocity along Z",
                    "Current world-space Z axis linear velocity component.",
                    "car.vel.z",
                    "car.vel.z > 2",
                    PhysicsSandboxCudaConditionValue::Velocity,
                    3u),
            MakeScalarSymbol(
                    "car.prev.vel.x",
                    {"car.prev.vel.x", "car.prev.velocity.x"},
                    "Previous velocity X",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car previous velocity X component",
                    "Car world-space X axis linear velocity one tick earlier.",
                    "car.prev.vel.x",
                    "car.prev.vel.x < 0",
                    PhysicsSandboxCudaConditionValue::PreviousVelocity,
                    1u),
            MakeScalarSymbol(
                    "car.prev.vel.y",
                    {"car.prev.vel.y", "car.prev.velocity.y"},
                    "Previous velocity Y",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car previous velocity Y component",
                    "Car world-space Y axis linear velocity one tick earlier.",
                    "car.prev.vel.y",
                    "car.prev.vel.y < 0",
                    PhysicsSandboxCudaConditionValue::PreviousVelocity,
                    2u),
            MakeScalarSymbol(
                    "car.prev.vel.z",
                    {"car.prev.vel.z", "car.prev.velocity.z"},
                    "Previous velocity Z",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car previous velocity Z component",
                    "Car world-space Z axis linear velocity one tick earlier.",
                    "car.prev.vel.z",
                    "car.prev.vel.z < 0",
                    PhysicsSandboxCudaConditionValue::PreviousVelocity,
                    3u),
            MakeScalarSymbol(
                    "car.vel.pitch",
                    {"car.vel.pitch", "car.velocity.pitch"},
                    "Current angular velocity pitch",
                    "vehicle",
                    "scalar",
                    "rad/s",
                    "car angular velocity pitch component",
                    "Current local-space pitch angular velocity.",
                    "car.vel.pitch",
                    "car.vel.pitch > 0",
                    PhysicsSandboxCudaConditionValue::AngularVelocity,
                    1u),
            MakeScalarSymbol(
                    "car.vel.yaw",
                    {"car.vel.yaw", "car.velocity.yaw"},
                    "Current angular velocity yaw",
                    "vehicle",
                    "scalar",
                    "rad/s",
                    "car angular velocity yaw component",
                    "Current local-space yaw angular velocity.",
                    "car.vel.yaw",
                    "car.vel.yaw > 0",
                    PhysicsSandboxCudaConditionValue::AngularVelocity,
                    2u),
            MakeScalarSymbol(
                    "car.vel.roll",
                    {"car.vel.roll", "car.velocity.roll"},
                    "Current angular velocity roll",
                    "vehicle",
                    "scalar",
                    "rad/s",
                    "car angular velocity roll component",
                    "Current local-space roll angular velocity.",
                    "car.vel.roll",
                    "car.vel.roll > 0",
                    PhysicsSandboxCudaConditionValue::AngularVelocity,
                    3u),
            MakeScalarSymbol(
                    "car.prev.vel.pitch",
                    {"car.prev.vel.pitch", "car.prev.velocity.pitch"},
                    "Previous angular velocity pitch",
                    "vehicle",
                    "scalar",
                    "rad/s",
                    "car previous angular velocity pitch",
                    "Previous local-space pitch angular velocity.",
                    "car.prev.vel.pitch",
                    "car.prev.vel.pitch > 0",
                    PhysicsSandboxCudaConditionValue::PreviousAngularVelocity,
                    1u),
            MakeScalarSymbol(
                    "car.prev.vel.yaw",
                    {"car.prev.vel.yaw", "car.prev.velocity.yaw"},
                    "Previous angular velocity yaw",
                    "vehicle",
                    "scalar",
                    "rad/s",
                    "car previous angular velocity yaw",
                    "Previous local-space yaw angular velocity.",
                    "car.prev.vel.yaw",
                    "car.prev.vel.yaw > 0",
                    PhysicsSandboxCudaConditionValue::PreviousAngularVelocity,
                    2u),
            MakeScalarSymbol(
                    "car.prev.vel.roll",
                    {"car.prev.vel.roll", "car.prev.velocity.roll"},
                    "Previous angular velocity roll",
                    "vehicle",
                    "scalar",
                    "rad/s",
                    "car previous angular velocity roll",
                    "Previous local-space roll angular velocity.",
                    "car.prev.vel.roll",
                    "car.prev.vel.roll > 0",
                    PhysicsSandboxCudaConditionValue::PreviousAngularVelocity,
                    3u),
            MakeScalarSymbol(
                    "car.localvel.x",
                    {"car.localvel.x", "car.localvelocity.x"},
                    "Current local velocity X",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car local velocity X component",
                    "Current local-space X axis speed component.",
                    "car.localvel.x",
                    "car.localvel.x > 2",
                    PhysicsSandboxCudaConditionValue::LocalVelocity,
                    1u),
            MakeScalarSymbol(
                    "car.localvel.y",
                    {"car.localvel.y", "car.localvelocity.y"},
                    "Current local velocity Y",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car local velocity Y component",
                    "Current local-space Y axis speed component.",
                    "car.localvel.y",
                    "car.localvel.y > 2",
                    PhysicsSandboxCudaConditionValue::LocalVelocity,
                    2u),
            MakeScalarSymbol(
                    "car.localvel.z",
                    {"car.localvel.z", "car.localvelocity.z"},
                    "Current local velocity Z",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car local velocity Z component",
                    "Current local-space Z axis speed component.",
                    "car.localvel.z",
                    "car.localvel.z > 2",
                    PhysicsSandboxCudaConditionValue::LocalVelocity,
                    3u),
            MakeScalarSymbol(
                    "car.prev.localvel.x",
                    {"car.prev.localvel.x", "car.prev.localvelocity.x"},
                    "Previous local velocity X",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car previous local velocity X component",
                    "Previous local-space X axis speed component.",
                    "car.prev.localvel.x",
                    "car.prev.localvel.x > 2",
                    PhysicsSandboxCudaConditionValue::PreviousLocalVelocity,
                    1u),
            MakeScalarSymbol(
                    "car.prev.localvel.y",
                    {"car.prev.localvel.y", "car.prev.localvelocity.y"},
                    "Previous local velocity Y",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car previous local velocity Y component",
                    "Previous local-space Y axis speed component.",
                    "car.prev.localvel.y",
                    "car.prev.localvel.y > 2",
                    PhysicsSandboxCudaConditionValue::PreviousLocalVelocity,
                    2u),
            MakeScalarSymbol(
                    "car.prev.localvel.z",
                    {"car.prev.localvel.z", "car.prev.localvelocity.z"},
                    "Previous local velocity Z",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "car previous local velocity Z component",
                    "Previous local-space Z axis speed component.",
                    "car.prev.localvel.z",
                    "car.prev.localvel.z > 2",
                    PhysicsSandboxCudaConditionValue::PreviousLocalVelocity,
                    3u),
            MakeScalarSymbol(
                    "car.speed",
                    {"car.speed"},
                    "Current speed",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "current scalar speed",
                    "Current car speed (velocity magnitude).",
                    "car.speed",
                    "car.speed > 40",
                    PhysicsSandboxCudaConditionValue::Speed,
                    0u),
            MakeScalarSymbol(
                    "car.prev.speed",
                    {"car.prev.speed"},
                    "Previous speed",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "previous scalar speed",
                    "Car speed one tick earlier.",
                    "car.prev.speed",
                    "car.prev.speed > 40",
                    PhysicsSandboxCudaConditionValue::PreviousSpeed,
                    0u),
            MakeScalarSymbol(
                    "car.localspeed",
                    {"car.localspeed"},
                    "Current local speed",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "local-frame speed magnitude",
                    "Current local-frame speed magnitude.",
                    "car.localspeed",
                    "car.localspeed > 40",
                    PhysicsSandboxCudaConditionValue::LocalSpeed,
                    0u),
            MakeScalarSymbol(
                    "car.prev.localspeed",
                    {"car.prev.localspeed"},
                    "Previous local speed",
                    "vehicle",
                    "scalar",
                    "m/s",
                    "previous local-frame speed",
                    "Local speed one tick earlier.",
                    "car.prev.localspeed",
                    "car.prev.localspeed > 40",
                    PhysicsSandboxCudaConditionValue::PreviousLocalSpeed,
                    0u),
            MakeScalarSymbol(
                    "car.yaw",
                    {"car.yaw", "car.rotation.yaw"},
                    "Current yaw",
                    "vehicle",
                    "scalar",
                    "rad",
                    "current yaw rotation",
                    "Current car yaw rotation.",
                    "car.yaw",
                    "car.yaw = 0",
                    PhysicsSandboxCudaConditionValue::Yaw,
                    0u),
            MakeScalarSymbol(
                    "car.pitch",
                    {"car.pitch", "car.rotation.pitch"},
                    "Current pitch",
                    "vehicle",
                    "scalar",
                    "rad",
                    "current pitch rotation",
                    "Current car pitch rotation.",
                    "car.pitch",
                    "car.pitch = 0",
                    PhysicsSandboxCudaConditionValue::Pitch,
                    0u),
            MakeScalarSymbol(
                    "car.roll",
                    {"car.roll", "car.rotation.roll"},
                    "Current roll",
                    "vehicle",
                    "scalar",
                    "rad",
                    "current roll rotation",
                    "Current car roll rotation.",
                    "car.roll",
                    "car.roll = 0",
                    PhysicsSandboxCudaConditionValue::Roll,
                    0u),
            MakeScalarSymbol(
                    "car.prev.yaw",
                    {"car.prev.yaw", "car.prev.rotation.yaw"},
                    "Previous yaw",
                    "vehicle",
                    "scalar",
                    "rad",
                    "previous yaw rotation",
                    "Car yaw rotation one tick earlier.",
                    "car.prev.yaw",
                    "car.prev.yaw = 0",
                    PhysicsSandboxCudaConditionValue::PreviousYaw,
                    0u),
            MakeScalarSymbol(
                    "car.prev.pitch",
                    {"car.prev.pitch", "car.prev.rotation.pitch"},
                    "Previous pitch",
                    "vehicle",
                    "scalar",
                    "rad",
                    "previous pitch rotation",
                    "Car pitch rotation one tick earlier.",
                    "car.prev.pitch",
                    "car.prev.pitch = 0",
                    PhysicsSandboxCudaConditionValue::PreviousPitch,
                    0u),
            MakeScalarSymbol(
                    "car.prev.roll",
                    {"car.prev.roll", "car.prev.rotation.roll"},
                    "Previous roll",
                    "vehicle",
                    "scalar",
                    "rad",
                    "previous roll rotation",
                    "Car roll rotation one tick earlier.",
                    "car.prev.roll",
                    "car.prev.roll = 0",
                    PhysicsSandboxCudaConditionValue::PreviousRoll,
                    0u),
            MakeScalarSymbol(
                    "car.freewheel",
                    {"car.freewheel"},
                    "Freewheel state",
                    "vehicle",
                    "scalar",
                    "bool",
                    "freewheel flag",
                    "Current freewheel status (0 or 1).",
                    "car.freewheel",
                    "car.freewheel = 1",
                    PhysicsSandboxCudaConditionValue::FreeWheeling,
                    0u),
            MakeScalarSymbol(
                    "car.lateralcontact",
                    {"car.lateralcontact"},
                    "Lateral contact",
                    "vehicle",
                    "scalar",
                    "bool",
                    "lateral contact status",
                    "Current lateral contact flag.",
                    "car.lateralcontact",
                    "car.lateralcontact = 1",
                    PhysicsSandboxCudaConditionValue::LateralContact,
                    0u),
            MakeScalarSymbol(
                    "car.sliding",
                    {"car.sliding", "car.is_sliding", "car.is"},
                    "Sliding state",
                    "vehicle",
                    "scalar",
                    "bool",
                    "sliding status",
                    "Current sliding flag.",
                    "car.is_sliding",
                    "car.is_sliding = 0",
                    PhysicsSandboxCudaConditionValue::Sliding,
                    0u),
            MakeScalarSymbol("car.gear",
                             {"car.gear"},
                             "Gear",
                             "vehicle",
                             "scalar",
                             "index",
                             "current transmission gear",
                             "Current selected gear value.",
                             "car.gear",
                             "car.gear = 1",
                             PhysicsSandboxCudaConditionValue::Gear,
                             0u),
            MakeScalarSymbol("car.rpm",
                             {"car.rpm"},
                             "RPM",
                             "vehicle",
                             "scalar",
                             "rpm",
                             "engine revolutions per minute",
                             "Current engine RPM.",
                             "car.rpm",
                             "car.rpm > 2000",
                             PhysicsSandboxCudaConditionValue::Rpm,
                             0u),
            MakeScalarSymbol("car.turning_rate",
                             {"car.turning_rate", "car.tr"},
                             "Turning rate",
                             "vehicle",
                             "scalar",
                             "rad/s",
                             "steering turning rate",
                             "Current steering steering rate.",
                             "car.tr",
                             "car.tr > 0.1",
                             PhysicsSandboxCudaConditionValue::TurningRate,
                             0u),
            MakeScalarSymbol("car.turbo_type",
                             {"car.turbo_type", "car.tt"},
                             "Turbo type",
                             "vehicle",
                             "scalar",
                             "index",
                             "turbo type",
                             "Current turbo mode identifier.",
                             "car.tt",
                             "car.tt >= 0",
                             PhysicsSandboxCudaConditionValue::TurboType,
                             0u),
            MakeScalarSymbol("car.turbo_boost_factor",
                             {"car.turbo_boost_factor", "car.tbf"},
                             "Turbo boost factor",
                             "vehicle",
                             "scalar",
                             "ratio",
                             "turbo boost factor",
                             "Current turbo boost multiplier.",
                             "car.tbf",
                             "car.tbf > 1",
                             PhysicsSandboxCudaConditionValue::TurboBoostFactor,
                             0u),
            MakeScalarSymbol("iterations",
                             {"iterations"},
                             "Iterations",
                             "search-state",
                             "scalar",
                             "count",
                             "search iteration index",
                             "Global search iteration counter.",
                             "iterations",
                             "iterations > 0",
                             PhysicsSandboxCudaConditionValue::Iterations,
                             0u),
            MakeScalarSymbol("last_improvement.time",
                             {"last_improvement.time"},
                             "Last improvement time",
                             "search-state",
                             "scalar",
                             "s",
                             "time of last improvement",
                             "Search state: time of the last improvement in seconds.",
                             "last_improvement.time",
                             "last_improvement.time >= 0",
                             PhysicsSandboxCudaConditionValue::LastImprovementTime,
                             0u),
            MakeScalarSymbol("last_restart.time",
                             {"last_restart.time"},
                             "Last restart time",
                             "search-state",
                             "scalar",
                             "s",
                             "time of last restart",
                             "Search state: time of the last restart in seconds.",
                             "last_restart.time",
                             "last_restart.time >= 0",
                             PhysicsSandboxCudaConditionValue::LastRestartTime,
                             0u),
            MakeScalarSymbol("car.wheels.frontleft.groundcontact",
                             {"car.wheels.frontleft.groundcontact"},
                             "Front-left wheel ground contact",
                             "vehicle",
                             "scalar",
                             "bool",
                             "front-left wheel ground contact",
                             "Whether the front-left wheel touches the ground.",
                             "car.wheels.frontleft.groundcontact",
                             "car.wheels.frontleft.groundcontact = 1",
                             PhysicsSandboxCudaConditionValue::WheelGroundContact0,
                             0u),
            MakeScalarSymbol("car.wheels.frontright.groundcontact",
                             {"car.wheels.frontright.groundcontact"},
                             "Front-right wheel ground contact",
                             "vehicle",
                             "scalar",
                             "bool",
                             "front-right wheel ground contact",
                             "Whether the front-right wheel touches the ground.",
                             "car.wheels.frontright.groundcontact",
                             "car.wheels.frontright.groundcontact = 1",
                             PhysicsSandboxCudaConditionValue::WheelGroundContact1,
                             0u),
            MakeScalarSymbol("car.wheels.backleft.groundcontact",
                             {"car.wheels.backleft.groundcontact"},
                             "Back-left wheel ground contact",
                             "vehicle",
                             "scalar",
                             "bool",
                             "back-left wheel ground contact",
                             "Whether the back-left wheel touches the ground.",
                             "car.wheels.backleft.groundcontact",
                             "car.wheels.backleft.groundcontact = 1",
                             PhysicsSandboxCudaConditionValue::WheelGroundContact2,
                             0u),
            MakeScalarSymbol("car.wheels.backright.groundcontact",
                             {"car.wheels.backright.groundcontact"},
                             "Back-right wheel ground contact",
                             "vehicle",
                             "scalar",
                             "bool",
                             "back-right wheel ground contact",
                             "Whether the back-right wheel touches the ground.",
                             "car.wheels.backright.groundcontact",
                             "car.wheels.backright.groundcontact = 1",
                             PhysicsSandboxCudaConditionValue::WheelGroundContact3,
                             0u),
            MakeScalarSymbol("car.wheels.frontleft.is",
                             {"car.wheels.frontleft.is", "car.wheels.frontleft.is_sliding"},
                             "Front-left wheel sliding",
                             "vehicle",
                             "scalar",
                             "bool",
                             "front-left wheel sliding",
                             "Whether the front-left wheel is sliding.",
                             "car.wheels.frontleft.is",
                             "car.wheels.frontleft.is = 0",
                             PhysicsSandboxCudaConditionValue::WheelSliding0,
                             0u),
            MakeScalarSymbol("car.wheels.frontright.is",
                             {"car.wheels.frontright.is", "car.wheels.frontright.is_sliding"},
                             "Front-right wheel sliding",
                             "vehicle",
                             "scalar",
                             "bool",
                             "front-right wheel sliding",
                             "Whether the front-right wheel is sliding.",
                             "car.wheels.frontright.is",
                             "car.wheels.frontright.is = 0",
                             PhysicsSandboxCudaConditionValue::WheelSliding1,
                             0u),
            MakeScalarSymbol("car.wheels.backleft.is",
                             {"car.wheels.backleft.is", "car.wheels.backleft.is_sliding"},
                             "Back-left wheel sliding",
                             "vehicle",
                             "scalar",
                             "bool",
                             "back-left wheel sliding",
                             "Whether the back-left wheel is sliding.",
                             "car.wheels.backleft.is",
                             "car.wheels.backleft.is = 0",
                             PhysicsSandboxCudaConditionValue::WheelSliding2,
                             0u),
            MakeScalarSymbol("car.wheels.backright.is",
                             {"car.wheels.backright.is", "car.wheels.backright.is_sliding"},
                             "Back-right wheel sliding",
                             "vehicle",
                             "scalar",
                             "bool",
                             "back-right wheel sliding",
                             "Whether the back-right wheel is sliding.",
                             "car.wheels.backright.is",
                             "car.wheels.backright.is = 0",
                             PhysicsSandboxCudaConditionValue::WheelSliding3,
                             0u),
            MakeScalarSymbol("car.wheels.frontleft.surface",
                             {"car.wheels.frontleft.surface"},
                             "Front-left wheel surface",
                             "vehicle",
                             "scalar",
                             "index",
                             "front-left wheel surface",
                             "Current surface identifier below the front-left wheel.",
                             "car.wheels.frontleft.surface",
                             "car.wheels.frontleft.surface >= 0",
                             PhysicsSandboxCudaConditionValue::WheelSurface0,
                             0u),
            MakeScalarSymbol("car.wheels.frontright.surface",
                             {"car.wheels.frontright.surface"},
                             "Front-right wheel surface",
                             "vehicle",
                             "scalar",
                             "index",
                             "front-right wheel surface",
                             "Current surface identifier below the front-right wheel.",
                             "car.wheels.frontright.surface",
                             "car.wheels.frontright.surface >= 0",
                             PhysicsSandboxCudaConditionValue::WheelSurface1,
                             0u),
            MakeScalarSymbol("car.wheels.backleft.surface",
                             {"car.wheels.backleft.surface"},
                             "Back-left wheel surface",
                             "vehicle",
                             "scalar",
                             "index",
                             "back-left wheel surface",
                             "Current surface identifier below the back-left wheel.",
                             "car.wheels.backleft.surface",
                             "car.wheels.backleft.surface >= 0",
                             PhysicsSandboxCudaConditionValue::WheelSurface2,
                             0u),
            MakeScalarSymbol("car.wheels.backright.surface",
                             {"car.wheels.backright.surface"},
                             "Back-right wheel surface",
                             "vehicle",
                             "scalar",
                             "index",
                             "back-right wheel surface",
                             "Current surface identifier below the back-right wheel.",
                             "car.wheels.backright.surface",
                             "car.wheels.backright.surface >= 0",
                             PhysicsSandboxCudaConditionValue::WheelSurface3,
                             0u),
            MakeVectorSymbol("car.pos",
                             {"car.pos", "car.position"},
                             "Current position",
                             "vehicle",
                             "vector",
                             "m",
                             "current car position",
                             "Current car world position.",
                             "car.pos",
                             "distance(car.pos, car.pos) = 0",
                             PhysicsSandboxCudaConditionValue::Position),
            MakeVectorSymbol("car.prev.pos",
                             {"car.prev.pos", "car.prev.position"},
                             "Previous position",
                             "vehicle",
                             "vector",
                             "m",
                             "previous car position",
                             "Car world position one tick earlier.",
                             "car.prev.pos",
                             "distance(car.prev.pos, car.prev.pos) = 0",
                             PhysicsSandboxCudaConditionValue::PreviousPosition),
            MakeVectorSymbol("car.vel",
                             {"car.vel", "car.velocity"},
                             "Current velocity",
                             "vehicle",
                             "vector",
                             "m/s",
                             "current velocity",
                             "Current car linear velocity vector.",
                             "car.vel",
                             "distance(car.vel, (0,0,0)) = 0",
                             PhysicsSandboxCudaConditionValue::Velocity),
            MakeVectorSymbol("car.prev.vel",
                             {"car.prev.vel", "car.prev.velocity"},
                             "Previous velocity",
                             "vehicle",
                             "vector",
                             "m/s",
                             "previous velocity",
                             "Car linear velocity one tick earlier.",
                             "car.prev.vel",
                             "distance(car.prev.vel, (0,0,0)) = 0",
                             PhysicsSandboxCudaConditionValue::PreviousVelocity),
            MakeVectorSymbol("car.localvel",
                             {"car.localvel", "car.localvelocity"},
                             "Current local velocity",
                             "vehicle",
                             "vector",
                             "m/s",
                             "current local velocity",
                             "Current car local-space velocity vector.",
                             "car.localvel",
                             "distance(car.localvel, (0,0,0)) = 0",
                             PhysicsSandboxCudaConditionValue::LocalVelocity),
            MakeVectorSymbol("car.prev.localvel",
                             {"car.prev.localvel", "car.prev.localvelocity"},
                             "Previous local velocity",
                             "vehicle",
                             "vector",
                             "m/s",
                             "previous local velocity",
                             "Car local-space velocity one tick earlier.",
                             "car.prev.localvel",
                             "distance(car.prev.localvel, (0,0,0)) = 0",
                             PhysicsSandboxCudaConditionValue::PreviousLocalVelocity),
            MakeVectorSymbol("bf_target_point",
                             {"bf_target_point"},
                             "Point target",
                             "point-target",
                             "vector",
                             "m",
                             "active point target vector",
                             "Active point target for point-target sessions.",
                             "variable(bf_target_point)",
                             "distance(car.pos, variable(bf_target_point)) < 5",
                             PhysicsSandboxCudaConditionValue::CurrentTime,
                             true,
                             true),
    };
    return symbols;
}

const std::vector<ConditionLanguageFunction> &AllConditionFunctions() {
    static const std::vector<ConditionLanguageFunction> functions = {
            MakeFunction("kmh",
                         {"kmh"},
                         "Kilometers per hour",
                         "arithmetic",
                         "kmh(scalar)",
                         "scalar",
                         "Converts m/s into km/h.",
                         "kmh(<x>)",
                         "kmh(car.speed) > 100",
                         ConditionLanguageFunctionKind::KmH),
            MakeFunction("deg",
                         {"deg"},
                         "Degrees",
                         "arithmetic",
                         "deg(scalar)",
                         "scalar",
                         "Converts radians into degrees.",
                         "deg(<x>)",
                         "deg(car.pitch) = 0",
                         ConditionLanguageFunctionKind::Deg),
            MakeFunction("time_since",
                         {"time_since"},
                         "Time since",
                         "search-state",
                         "time_since(scalar)",
                         "scalar",
                         "Subtracts a scalar value from the current search time.",
                         "time_since(<x>)",
                         "time_since(last_improvement.time) = 0",
                         ConditionLanguageFunctionKind::TimeSince),
            MakeFunction("distance",
                         {"distance"},
                         "Distance",
                         "vector",
                         "distance(vector, vector)",
                         "scalar",
                         "Euclidean distance between two vectors.",
                         "distance(<v1>, <v2>)",
                         "distance(car.pos, (0,0,0)) < 5",
                         ConditionLanguageFunctionKind::Distance),
            MakeFunction("variable",
                         {"variable", "var"},
                         "External variable",
                         "lookup",
                         "variable(name)",
                         "scalar or vector",
                         "Reads user-provided variables by exact key.",
                         "variable(name)",
                         "distance(car.pos, variable(bf_target_point)) < 5",
                         ConditionLanguageFunctionKind::VariableLookup,
                         true),
    };
    return functions;
}

}  // namespace

const std::vector<ConditionLanguageSymbol> &GetConditionSymbols() {
    return AllConditionSymbols();
}

const std::vector<ConditionLanguageFunction> &GetConditionFunctions() {
    return AllConditionFunctions();
}

bool MatchesSymbolName(std::string_view normalized,
                      const ConditionLanguageSymbol &symbol) {
    if (symbol.canonicalName == normalized) return true;
    return std::find(symbol.aliases.begin(), symbol.aliases.end(), normalized) !=
            symbol.aliases.end();
}

const ConditionLanguageSymbol *FindConditionSymbol(std::string_view name) {
    const std::string normalized = Lower(name);
    for (const ConditionLanguageSymbol &symbol : GetConditionSymbols()) {
        if (MatchesSymbolName(normalized, symbol)) return &symbol;
    }
    return nullptr;
}

const ConditionLanguageFunction *FindConditionFunction(std::string_view name) {
    const std::string normalized = Lower(name);
    for (const ConditionLanguageFunction &function : GetConditionFunctions()) {
        if (function.canonicalName == normalized) return &function;
        if (std::find(function.aliases.begin(), function.aliases.end(),
                      normalized) != function.aliases.end()) {
            return &function;
        }
    }
    return nullptr;
}

std::optional<ConditionLanguageSymbolResolution> ResolveConditionSymbol(
        std::string_view name) {
    const auto *const symbol = FindConditionSymbol(name);
    if (symbol == nullptr || symbol->external) return std::nullopt;
    return ConditionLanguageSymbolResolution{symbol, symbol->sourceValue,
                                           symbol->sourceComponent};
}

}  // namespace forevertas
